# Jekyll configuration

name: Aric's Project Blog
description: Electrical Engineer

# Url is currently only used only for the RSS feed in feed.xml
#url: http://streetturtle.github.io
#url: http://localhost:4000
url: http://aricbeaver.com

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
# baseurl: '/jekyll-clean-dark'
baseurl: ''

share:
  facebook: true
  twitter: false
  gplus: false
  linkedin: true
  pinterest: false
  email: true

social:
  github: aricbeaver
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  rss:

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-98379798-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica: true


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: aricbeaver
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
  auto_ids: true
  syntax_highlighter: rouge

exclude: ['README.md', 'LICENSE']
